[tool.poetry]
name = "espnbaseballautostart"
version = "0.1.0"
description = ""
authors = ["Ballin2much <smomark12@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
selenium = "^4.8.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"